const DeleteProductType = {
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAIL: 'DELETE_PRODUCT_FAIL',
    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
};

export default DeleteProductType;