const UpdateProductType = {
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAIL: 'UPDATE_PRODUCT_FAIL',
    UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
};

export default UpdateProductType;
