const CreateCategoryType = {
    CATEGORIES_CREATE_SUCCESS: 'CATEGORIES_CREATE_SUCCESS',
    CATEGORIES_CREATE_FAILURE: 'CATEGORIES_CREATE_FAILURE',
    SET_LOADING: 'SET_LOADING',
};

export default CreateCategoryType;
