const DeleteCategoryType = {
    DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_FAIL: "DELETE_CATEGORY_FAIL",
    DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
};

export default DeleteCategoryType;