const CreateSupplierType = {
    CREATE_SUPPLIER_SUCCESS: 'CREATE_SUPPLIER_SUCCESS',
    CREATE_SUPPLIER_FAIL: 'CREATE_SUPPLIER_FAIL',
    CREATE_SUPPLIER_REQUEST: 'CREATE_SUPPLIER_REQUEST',
};

export default CreateSupplierType;