const DeleteSupplierType = {
    DELETE_SUPPLIER_REQUEST: "DELETE_SUPPLIER_REQUEST",
    DELETE_SUPPLIER_SUCCESS: "DELETE_SUPPLIER_SUCCESS",
    DELETE_SUPPLIER_FAIL: "DELETE_SUPPLIER_FAIL",
};

export default DeleteSupplierType;
