const UpdateSupplierType = {
    UPDATE_SUPPLIER_REQUEST: "UPDATE_SUPPLIER_REQUEST",
    UPDATE_SUPPLIER_SUCCESS: "UPDATE_SUPPLIER_SUCCESS",
    UPDATE_SUPPLIER_FAIL: "UPDATE_SUPPLIER_FAIL",
};

export default UpdateSupplierType;
