import FooterComponent from "@/components/FooterComponent";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}

        <footer>
          <FooterComponent />
        </footer>
      </body>
    </html>
  );
}
