const CreateStockType = {
    CREATE_STOCK_REQUEST: 'CREATE_STOCK_REQUEST',
    CREATE_STOCK_SUCCESS: 'CREATE_STOCK_SUCCESS',
    CREATE_STOCK_FAILURE: 'CREATE_STOCK_FAILURE'
};

export default CreateStockType ;