export const ProfileType = {
    GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
    GET_PROFILE_FAIL: "GET_PROFILE_FAIL",
    UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAIL: "UPDATE_PROFILE_FAIL",
};