name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout the repository
      - run: npm ci && npm run build  # Install dependencies and build the Next.js app
      - uses: FirebaseExtended/action-hosting-deploy@v0  # Firebase Hosting deploy action
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INVENTORY_CSW }}  # Firebase service account key
          channelId: live  # Deploy to the live channel
          projectId: inventory-csw  # Firebase project ID
